name: test-build

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependencies
        run: npm install
      - name: Write Environment File
        uses: DamianReeves/write-file-action@master
        with:
          path: .env.local
          contents: ${{ secrets.ENV_LOCAL }}
          write-mode: overwrite
      - name: Test a Build
        run: npm run build
